/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pasien;

import DB_koneksi.DB;
import auth.splash;
import dashboard.dashboard;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ScrollPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakab
 */
public class pasien extends javax.swing.JFrame {

    /**
     * Creates new form pasien
     */
    boolean isOnUpdate = false;

    public pasien() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setUndecorated(true);

        initComponents();
        // Mengatur ukuran jendela
        this.setSize(1920, 1080); // Atur ukuran sesuai kebutuhan
        this.setLocationRelativeTo(null);
        getPasien();
        tambah_act.setVisible(false);
        simpan_bgdark2.setVisible(false);
    }

    public void getPasien() {
        try {
            String lastNoAntrian = "";
            DefaultTableModel tblModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tblModel.addColumn("No. Antrian");
            tblModel.addColumn("Nama Pasien");
            tblModel.addColumn("NIK Pasien");
            String sql = "SELECT * FROM pasien";
            Statement statement = DB.getConnection().createStatement();
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                String no_antrian = resultSet.getString("no_antrian");
                String nama_pasien = resultSet.getString("nama_pasien");
                String nik_pasien = resultSet.getString("nik");
                tblModel.addRow(new Object[]{no_antrian, nama_pasien, nik_pasien});
                lastNoAntrian = no_antrian;
//                System.out.printf(": %s, Name: %s, Email: %s%n", no_antrian, nama_pasien, nik_pasien);
            }
            tblPasien.setModel(tblModel);
            tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int selectedRow = tblPasien.getSelectedRow();

                    if (selectedRow != -1) {
                        String noAntrian = tblPasien.getValueAt(selectedRow, 0).toString();
                        String namaPasien = tblPasien.getValueAt(selectedRow, 1).toString();
                        String nikPasien = tblPasien.getValueAt(selectedRow, 2).toString();

                        nomor_antrian_field.setText(noAntrian);
                        nama_pasien_field.setText(namaPasien);
                        nik_field.setText(nikPasien);
                        simpan_btn.setText("Ubah");
                        isOnUpdate = true;
                        tambah_act.setVisible(true);
                        simpan_bgdark2.setVisible(true);
                    }
                }
            });
            String[] splittedNoAntrian = lastNoAntrian.split("-");
            System.out.println();
            String incrementedNoAntrian = splittedNoAntrian[0] + "-" + String.valueOf(Integer.parseInt(splittedNoAntrian[1]) + 1);
            nomor_antrian_field.setText(incrementedNoAntrian);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dafpasien_txt = new javax.swing.JLabel();
        nama_pasien = new javax.swing.JLabel();
        nik_txt = new javax.swing.JLabel();
        no_antrian_txt = new javax.swing.JLabel();
        nik_field = new javax.swing.JTextField();
        nama_pasien_field = new javax.swing.JTextField();
        nomor_antrian_field = new javax.swing.JTextField();
        nik_grey = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        namapasien_grey1 = new javax.swing.JLabel();
        antrian_grey1 = new javax.swing.JLabel();
        icon_signout = new javax.swing.JLabel();
        icon_home = new javax.swing.JLabel();
        navTop = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        tambah_act = new javax.swing.JLabel();
        simpan_bgdark2 = new javax.swing.JLabel();
        simpan_btn = new javax.swing.JLabel();
        simpan_bgdark = new javax.swing.JLabel();
        hps_btn = new javax.swing.JLabel();
        delete_bgdark = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dafpasien_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        dafpasien_txt.setForeground(new java.awt.Color(255, 255, 255));
        dafpasien_txt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dafpasien_txt.setText("Data Antrian Pasien");
        getContentPane().add(dafpasien_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 350, 50));

        nama_pasien.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        nama_pasien.setForeground(new java.awt.Color(52, 55, 217));
        nama_pasien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama_pasien.setText("Nama Pasien");
        getContentPane().add(nama_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 50));

        nik_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        nik_txt.setForeground(new java.awt.Color(52, 55, 217));
        nik_txt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nik_txt.setText("Nomor Induk Keluarga");
        getContentPane().add(nik_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 270, 50));

        no_antrian_txt.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        no_antrian_txt.setForeground(new java.awt.Color(52, 55, 217));
        no_antrian_txt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        no_antrian_txt.setText("Nomor Antrian");
        getContentPane().add(no_antrian_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 50));

        nik_field.setBackground(new java.awt.Color(225, 232, 237));
        nik_field.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        nik_field.setBorder(null);
        nik_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nik_fieldKeyReleased(evt);
            }
        });
        getContentPane().add(nik_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 430, 70));

        nama_pasien_field.setBackground(new java.awt.Color(225, 232, 237));
        nama_pasien_field.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        nama_pasien_field.setBorder(null);
        getContentPane().add(nama_pasien_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 420, 70));

        nomor_antrian_field.setEditable(false);
        nomor_antrian_field.setBackground(new java.awt.Color(225, 232, 237));
        nomor_antrian_field.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        nomor_antrian_field.setBorder(null);
        getContentPane().add(nomor_antrian_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 420, 70));

        nik_grey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectanglegrey.png"))); // NOI18N
        getContentPane().add(nik_grey, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 460, 90));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, 20, -1));

        namapasien_grey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectanglegrey.png"))); // NOI18N
        getContentPane().add(namapasien_grey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 460, 90));

        antrian_grey1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectanglegrey.png"))); // NOI18N
        getContentPane().add(antrian_grey1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 140, 460, 90));

        icon_signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_signout.png"))); // NOI18N
        icon_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_signoutMouseClicked(evt);
            }
        });
        getContentPane().add(icon_signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 1011, -1, 50));

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_home.png"))); // NOI18N
        icon_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_homeMouseClicked(evt);
            }
        });
        getContentPane().add(icon_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 970, -1, -1));

        navTop.setBackground(new java.awt.Color(250, 154, 156));

        javax.swing.GroupLayout navTopLayout = new javax.swing.GroupLayout(navTop);
        navTop.setLayout(navTopLayout);
        navTopLayout.setHorizontalGroup(
            navTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        navTopLayout.setVerticalGroup(
            navTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(navTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 60));

        sidepanel.setBackground(new java.awt.Color(217, 217, 217));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambah_act.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        tambah_act.setForeground(new java.awt.Color(255, 255, 255));
        tambah_act.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tambah_act.setText("Tambah Data");
        tambah_act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_actMouseClicked(evt);
            }
        });
        sidepanel.add(tambah_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 170, 40));

        simpan_bgdark2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectangledarkrey.png"))); // NOI18N
        sidepanel.add(simpan_bgdark2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, -1, 60));

        simpan_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        simpan_btn.setForeground(new java.awt.Color(255, 255, 255));
        simpan_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simpan_btn.setText("Simpan");
        simpan_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpan_btnMouseClicked(evt);
            }
        });
        sidepanel.add(simpan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 170, 60));

        simpan_bgdark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectangledarkrey.png"))); // NOI18N
        sidepanel.add(simpan_bgdark, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 60));

        hps_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        hps_btn.setForeground(new java.awt.Color(255, 255, 255));
        hps_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hps_btn.setText("Hapus");
        hps_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hps_btnMouseClicked(evt);
            }
        });
        sidepanel.add(hps_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 170, 60));

        delete_bgdark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectangledarkrey.png"))); // NOI18N
        sidepanel.add(delete_bgdark, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, 60));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 1020));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void icon_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_homeMouseClicked
        // TODO add your handling code here:
        dashboard dash = new dashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_icon_homeMouseClicked

    private void icon_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_signoutMouseClicked
        // TODO add your handling code here:
        splash front = new splash();
        this.dispose();
        front.setVisible(true);
    }//GEN-LAST:event_icon_signoutMouseClicked

    private void simpan_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpan_btnMouseClicked
        if (formValidation()) {
            if (!isOnUpdate) {
                try {
                    if (!checkNIKLength()) {
                        return;
                    }
                    String sql = "INSERT INTO pasien (no_antrian, nama_pasien, nik) VALUES (?, ?, ?)";
                    PreparedStatement preparedStatement = DB.getConnection().prepareStatement(sql);

                    String noAntrian = nomor_antrian_field.getText();
                    String namaPasien = nama_pasien_field.getText();
                    String nikPasien = nik_field.getText();

                    preparedStatement.setString(1, noAntrian); // Set no_antrian
                    preparedStatement.setString(2, namaPasien); // Set nama_pasien
                    preparedStatement.setString(3, nikPasien); // Set nik
                    int rowsInserted = preparedStatement.executeUpdate();
                    if (rowsInserted > 0) {
                        JOptionPane.showMessageDialog(null,
                                "Data berhasil ditambahkan ke database!",
                                "Sukses",
                                JOptionPane.INFORMATION_MESSAGE);
                        clearForm();
                        getPasien();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }

            } else {
                if (!checkNIKLength()) {
                    return;
                }
                String nomorAntrian = nomor_antrian_field.getText();
                String namaPasien = nama_pasien_field.getText();
                String nikPasien = nik_field.getText();

                int confirm = JOptionPane.showConfirmDialog(null,
                        "Apakah Anda yakin ingin mengubah data dengan No. Antrian " + nomorAntrian + "?",
                        "Konfirmasi Perubahan",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (confirm == JOptionPane.YES_OPTION) {
                    // Query untuk mengupdate data
                    String sql = "UPDATE pasien SET nama_pasien = ?, nik = ? WHERE no_antrian = ?";

                    try (PreparedStatement preparedStatement = DB.getConnection().prepareStatement(sql)) {
                        // Set parameter untuk query
                        preparedStatement.setString(1, namaPasien);
                        preparedStatement.setString(2, nikPasien);
                        preparedStatement.setString(3, nomorAntrian);

                        // Eksekusi query untuk update data
                        int rowsAffected = preparedStatement.executeUpdate();

                        if (rowsAffected > 0) {
                            // Jika berhasil, tampilkan pesan sukses
                            JOptionPane.showMessageDialog(null,
                                    "Data dengan No. Antrian " + nomorAntrian + " telah diperbarui.",
                                    "Sukses",
                                    JOptionPane.INFORMATION_MESSAGE);

                            // Panggil method untuk memperbarui tampilan tabel atau data
                            String tempNoAntrian = nomor_antrian_field.getText();
                            getPasien();
                            nomor_antrian_field.setText(tempNoAntrian);

                            // Clear form setelah update
//                        clearForm();
                        } else {
                            // Jika data tidak ditemukan atau update gagal
                            JOptionPane.showMessageDialog(null,
                                    "Data dengan No. Antrian " + nomorAntrian + " tidak ditemukan.",
                                    "Gagal",
                                    JOptionPane.ERROR_MESSAGE);
                        }

                    } catch (SQLException e) {
                        // Menangani error SQL
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error saat mengupdate data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    tblPasien.clearSelection();
                } else {
                    // Jika pengguna membatalkan perubahan
                    JOptionPane.showMessageDialog(null,
                            "Perubahan dibatalkan.",
                            "Batal",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Mohon untuk mengisi form dengan lengkap!",
                    "Tidak valid!",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_simpan_btnMouseClicked

    private void tambah_actMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_actMouseClicked
        isOnUpdate = false;
        simpan_btn.setText("Tambah");
        tblPasien.clearSelection();
        tambah_act.setVisible(false);
        simpan_bgdark2.setVisible(false);
        clearForm();
        getPasien();
    }//GEN-LAST:event_tambah_actMouseClicked

    private void hps_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hps_btnMouseClicked
        try {
            if (!isOnUpdate) {
                JOptionPane.showMessageDialog(null,
                        "Belum memilih data untuk dihapus!",
                        "Hapus data gagal!",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String sql = "DELETE FROM pasien WHERE no_antrian = ?";
            PreparedStatement preparedStatement = DB.getConnection().prepareStatement(sql);

            String nomorAntrian = nomor_antrian_field.getText();

            int confirm = JOptionPane.showConfirmDialog(null,
                    "Apakah kamu yakin ingin menghapus data dengan No. Antrian " + nomorAntrian + "?",
                    "Konfirmasi Hapus!",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                // Proceed with deleting the data if confirmed
                preparedStatement.setString(1, nomorAntrian);

                int rowsAffected = preparedStatement.executeUpdate();
                if (rowsAffected > 0) {
                    // Show success message
                    JOptionPane.showMessageDialog(null,
                            "Data dengan No. Antrian " + nomorAntrian + " telah dihapus dari database.",
                            "Sukses",
                            JOptionPane.INFORMATION_MESSAGE);

                    isOnUpdate = false;
                    simpan_btn.setText("Tambah");
                    tblPasien.clearSelection();
                    tambah_act.setVisible(false);
                    simpan_bgdark2.setVisible(false);
                    clearForm();
                    getPasien();
                }
            } else {
                // If the user clicked "No", show a cancellation message or do nothing
                JOptionPane.showMessageDialog(null,
                        "Penghapusan dibatalkan.",
                        "Batal",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_hps_btnMouseClicked

    public static boolean isValidInteger(String str) {
        return str.matches("-?\\d+");
    }

    private void nik_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nik_fieldKeyReleased
        if (isValidInteger(nik_field.getText())) {
            if (nik_field.getText().length() > 16) {
                nik_field.setText(nik_field.getText().substring(0, nik_field.getText().length() - 1));
                JOptionPane.showMessageDialog(null,
                        "NIK tidak boleh lebih dari 16 digit.!",
                        "Tidak valid!",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            nik_field.setText(null);
        }
    }//GEN-LAST:event_nik_fieldKeyReleased

    private boolean formValidation() {
        if (nomor_antrian_field.getText().isEmpty() || nik_field.getText().isEmpty() || nama_pasien_field.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean checkNIKLength() {
        if (nik_field.getText().length() > 16) {
            JOptionPane.showMessageDialog(null,
                    "NIK tidak boleh lebih dari 16 angka.!",
                    "Tidak Valid!",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    private void clearForm() {
        nomor_antrian_field.setText(null);
        nama_pasien_field.setText(null);
        nik_field.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antrian_grey1;
    private javax.swing.JLabel dafpasien_txt;
    private javax.swing.JLabel delete_bgdark;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel hps_btn;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_signout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama_pasien;
    private javax.swing.JTextField nama_pasien_field;
    private javax.swing.JLabel namapasien_grey1;
    private javax.swing.JPanel navTop;
    private javax.swing.JTextField nik_field;
    private javax.swing.JLabel nik_grey;
    private javax.swing.JLabel nik_txt;
    private javax.swing.JLabel no_antrian_txt;
    private javax.swing.JTextField nomor_antrian_field;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JLabel simpan_bgdark;
    private javax.swing.JLabel simpan_bgdark2;
    private javax.swing.JLabel simpan_btn;
    private javax.swing.JLabel tambah_act;
    // End of variables declaration//GEN-END:variables
}
