/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;

import dashboard.dashboard;
import javax.swing.JFrame;

/**
 *
 * @author sakab
 */
public class loginauth extends javax.swing.JFrame {

    /**
     * Creates new form loginauth
     */
    public loginauth() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setUndecorated(true);
        
        initComponents();
         // Mengatur ukuran jendela
        this.setSize(1920, 1080); // Atur ukuran sesuai kebutuhan
        this.setLocationRelativeTo(null); // Agar posisi center saat dibuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        logintext = new javax.swing.JLabel();
        userField1 = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        jCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        loginbutton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        registerbtn = new javax.swing.JLabel();
        usertext = new javax.swing.JLabel();
        bg_login = new javax.swing.JLabel();
        kemenkes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, 20, -1));

        passtext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        passtext.setForeground(new java.awt.Color(255, 255, 255));
        passtext.setText("Password");
        jPanel1.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 430, 160, 60));

        logintext.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        logintext.setForeground(new java.awt.Color(255, 255, 255));
        logintext.setText("Login Admin");
        jPanel1.add(logintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 60));

        userField1.setBackground(new java.awt.Color(255, 255, 255));
        userField1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        userField1.setForeground(new java.awt.Color(0, 0, 0));
        userField1.setBorder(null);
        userField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userField1ActionPerformed(evt);
            }
        });
        jPanel1.add(userField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 320, 590, 60));

        PassField.setBackground(new java.awt.Color(255, 255, 255));
        PassField.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setBorder(null);
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1074, 500, 590, 60));

        jCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox.setBorder(null);
        jCheckBox.setContentAreaFilled(false);
        jCheckBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/eye_icon.png"))); // NOI18N
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1666, 500, -1, 50));

        jPanel2.setBackground(new java.awt.Color(226, 79, 82));

        loginbutton.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbutton.setText("Login");
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 680, 80));

        jPanel3.setBackground(new java.awt.Color(226, 79, 82));

        registerbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerbtn.setText("Click here to create a new account");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 790, -1, 90));

        usertext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usertext.setForeground(new java.awt.Color(255, 255, 255));
        usertext.setText("Username");
        jPanel1.add(usertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 260, -1, 50));

        bg_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_login.png"))); // NOI18N
        jPanel1.add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 880));

        kemenkes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kemenkes_icon.png"))); // NOI18N
        jPanel1.add(kemenkes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, -1, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void userField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userField1ActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        // untuk melihat password
        if (jCheckBox.isSelected()) {
            PassField.setEchoChar((char) 0);
        } else {
            PassField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
        // TODO add your handling code here:
        register regis = new register();
        regis.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_registerbtnMouseClicked

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
        // TODO add your handling code here:
        dashboard dash = new dashboard();
        dash.setVisible(true); 
            
        this.dispose(); 
    }//GEN-LAST:event_loginbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginauth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginauth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel bg_login;
    private javax.swing.JLabel exit;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kemenkes;
    private javax.swing.JLabel loginbutton;
    private javax.swing.JLabel logintext;
    private javax.swing.JLabel passtext;
    private javax.swing.JLabel registerbtn;
    private javax.swing.JTextField userField1;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
