/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auth;

import javax.swing.JFrame;

/**
 *
 * @author sakab
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setUndecorated(true);
        
        initComponents();
         // Mengatur ukuran jendela
        this.setSize(1920, 1080); // Atur ukuran sesuai kebutuhan
        this.setLocationRelativeTo(null); // Agar posisi center saat dibuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kemenkes_icon = new javax.swing.JLabel();
        icon_regis = new javax.swing.JLabel();
        registext = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        firstNameField1 = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();
        AddressField = new javax.swing.JTextField();
        addresstext = new javax.swing.JLabel();
        passtext = new javax.swing.JLabel();
        lastnametext = new javax.swing.JLabel();
        firstnametext = new javax.swing.JLabel();
        usernametext = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        kembali = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        rectangle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kemenkes_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/kemenkes_icon.png"))); // NOI18N
        jPanel1.add(kemenkes_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, 90));

        icon_regis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_regis.png"))); // NOI18N
        jPanel1.add(icon_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 170));

        registext.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        registext.setForeground(new java.awt.Color(255, 255, 255));
        registext.setText("Register");
        jPanel1.add(registext, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 70));

        LastNameField.setBackground(new java.awt.Color(255, 255, 255));
        LastNameField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LastNameField.setForeground(new java.awt.Color(0, 0, 0));
        LastNameField.setToolTipText("");
        LastNameField.setBorder(null);
        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 990, 80));

        firstNameField1.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        firstNameField1.setForeground(new java.awt.Color(0, 0, 0));
        firstNameField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNameField1.setText("Saka");
        firstNameField1.setToolTipText("");
        firstNameField1.setBorder(null);
        firstNameField1.setMinimumSize(new java.awt.Dimension(1, 28));
        firstNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameField1ActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 990, 80));

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameField.setToolTipText("");
        UsernameField.setBorder(null);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 990, 80));

        PassField.setBackground(new java.awt.Color(255, 255, 255));
        PassField.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PassField.setForeground(new java.awt.Color(0, 0, 0));
        PassField.setBorder(null);
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 990, 80));

        AddressField.setBackground(new java.awt.Color(255, 255, 255));
        AddressField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        AddressField.setForeground(new java.awt.Color(0, 0, 0));
        AddressField.setToolTipText("");
        AddressField.setBorder(null);
        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 990, 80));

        addresstext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        addresstext.setForeground(new java.awt.Color(255, 255, 255));
        addresstext.setText("Address");
        jPanel1.add(addresstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, 50));

        passtext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        passtext.setForeground(new java.awt.Color(255, 255, 255));
        passtext.setText("Password");
        jPanel1.add(passtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 720, -1, 50));

        lastnametext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lastnametext.setForeground(new java.awt.Color(255, 255, 255));
        lastnametext.setText("Last Name");
        jPanel1.add(lastnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, 50));

        firstnametext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        firstnametext.setForeground(new java.awt.Color(255, 255, 255));
        firstnametext.setText("First Name");
        jPanel1.add(firstnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 50));

        usernametext.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        usernametext.setForeground(new java.awt.Color(255, 255, 255));
        usernametext.setText("Username");
        jPanel1.add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, 50));

        jPanel3.setBackground(new java.awt.Color(226, 79, 82));

        kembali.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kembali.setText("Kembali");
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 850, 420, 90));

        jPanel2.setBackground(new java.awt.Color(226, 79, 82));

        register.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Register");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 850, 420, 90));

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 10, 20, -1));

        rectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rectangle.png"))); // NOI18N
        jPanel1.add(rectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 880));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void firstNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameField1ActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        loginauth front = new loginauth();
        this.dispose();
        front.setVisible(true);
    }//GEN-LAST:event_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel addresstext;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField firstNameField1;
    private javax.swing.JLabel firstnametext;
    private javax.swing.JLabel icon_regis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel kemenkes_icon;
    private javax.swing.JLabel lastnametext;
    private javax.swing.JLabel passtext;
    private javax.swing.JLabel rectangle;
    private javax.swing.JLabel register;
    private javax.swing.JLabel registext;
    private javax.swing.JLabel usernametext;
    // End of variables declaration//GEN-END:variables
}
